# Procesos ETVL usando R -- 2 -- Programación
Notas de clase sobre la extracción, transformación, visualización y carga de datos usando R

**Juan David Velásquez Henao**   
jdvelasq@unal.edu.co  
Universidad Nacional de Colombia, Sede Medellín  
Facultad de Minas  
Medellín, Colombia  

[Licencia](https://github.com/jdvelasq/ETVL-R/blob/master/LICENCIA.txt)  
[Readme](https://github.com/jdvelasq/ETVL-R/blob/master/Readme.md)

**Software utilizado**

> Este es un documento interactivo escrito como un notebook de [Jupyter](http://jupyter.org), en el cual se presenta un tutorial sobre la extracción, transformación, visualización y carga de datos usando **R** en el contexto de la ciencia de los datos. Los notebooks de Jupyter permiten incoporar simultáneamente código, texto, gráficos y ecuaciones. El código presentado en este notebook puede ejecutarse en los sistemas operativos Linux y OS X.

> Haga click [aquí](https://github.com/jdvelasq/guias-de-instalacion) para obtener instrucciones detalladas sobre como instalar Jupyter en Windows y Mac OS X.

> Haga clic [aquí](http://nbviewer.jupyter.org/github/jdvelasq/ETVL-R/blob/master/ETVL-R-2-programacion.ipynb) para ver la última versión de este documento en nbviewer.

> Descargue la última versión de este documento a su disco duro; luego, carguelo y ejecutelo en línea en [Try Jupyter!](https://try.jupyter.org)

#### Contenido

> 
* [Estructuras de control](#Estructuras-de-control)
    * [Estructura  `if`](#Estructura--if)
    * [Estructura `for`](#Estructura-for)
    * [Comandos `break` y `next`](#Comandos-break-y-next)
    * [Estructura `while`](#Estructura-while)
    * [Estructura `repeat`](#Estructura-repeat)
* [Funciones](#Funciones)
* [Estructuras de Datos](#Estructuras-de-Datos)
    * [Vectores](#Vectores)
    * [Matrices](#Matrices)
    * [Funciones `lapply` ,  `apply` ](#Funciones-lapply-,--apply)
    * [Data frames](#Data-frames)
    * [Conjuntos](#Conjuntos)
    * [Uso de listas como dicionarios](#Uso-de-listas-como-dicionarios)
    * [Factores](#Factores)
    * [Strings](#Strings)
* [Impresión con formato](#Impresión-con-formato)
* [Ejecución de Python dentro de R](#Ejecución-de-Python-dentro-de-R)

**Bibliografía**.

> [An introduction to R](https://cran.r-project.org/doc/manuals/R-intro.pdf) by W. N. Venables, D. M. Smith and the R Core Team


# Estructuras de control

## Estructura  `if`

[Contenido](#Contenido)

En el lenguaje R se usan las llaves (`{` y `}`) para indicar el bloque de código correspondiente a cada estructura de control.

In [1]:
# x = as.integer(readline(prompt="Please enter an integer: ")) # no funciona en jupyter
x = 1
if (x < 0) {
    x = 0
    print('Negative changed to zero')
} else if (x == 0) {
    print('Zero')
} else if (x == 1) {
    print('Single')
} else {
    print('More')
}

[1] "Single"


In [2]:
x <- ifelse(2 > 1, '2 > 1!!!',  ' False  ')
x

[1] "2 > 1!!!"

## Estructura `for`

[Contenido](#Contenido)

El comando `for` permite iterar sobre los elementos de un vector.

In [3]:
words = c('cat', 'window', 'door', 'abcdefg')
for (w in words)
    cat(w, nchar(w), '\n')

cat 3 
window 6 
door 4 
abcdefg 7 


La función `seq(n)` devuelve un objeto cuyos elementos son los enteros consecutivos desde `1` hasta `n`.

In [4]:
for (i in seq(5))
    print(i)

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


In [5]:
seq(5)

[1] 1 2 3 4 5

In [6]:
for (i in seq(5, 10))
    cat(i, end = ', ', sep = '') # el argumento end indica que al final del print  
                                 # se imprime ', ' y no retorno de carro

5, 6, 7, 8, 9, 10, 

In [7]:
a = c('Mary', 'had', 'a', 'little', 'lamb')
for (i in seq(length(a)))
    cat(i, a[i], '\n')

1 Mary 
2 had 
3 a 
4 little 
5 lamb 


## Comandos `break` y `next`

[Contenido](#Contenido)

El comando `next` causa que se ejecute una nueva iteración del ciclo `for` sin pasar por el resto del código que hace parte del cuerpo del ciclo `for`. El comando `break` causa la salida del cuerpo del ciclo `for`.

In [8]:
for (n in seq(1, 10)) {
    if (n < 4)
        next
    print(n)   # solo pasa por aca cuando n >= 4.
    if (n > 6)
        break  # interrupe el ciclo cuando n > 6.
}
print('fin')

[1] 4
[1] 5
[1] 6
[1] 7
[1] "fin"


## Estructura `while`

[Contenido](#Contenido)

El comando `while` permite iterar mientras se cumpla una condición. Al igual que en un ciclo `for`, el código perteneciente al cuerpo del `while` se identifica por identación. 

In [9]:
n = 0
while (n < 10) {  # se ejecuta mientras se cumpla que n < 5
    if (n < 4) {
        n <- n +1
        next
    }
    print(n)   # solo pasa por aca cuando n >= 4.
    if (n > 6)
        break  # interrupe el ciclo cuando n > 6.
    n = n + 1
}   
print('fin')

[1] 4
[1] 5
[1] 6
[1] 7
[1] "fin"


## Estructura `repeat`

[Contenido](#Contenido)

In [10]:
n <- 0
repeat {  # es un ciclo infinito si no se coloca un break
    if (n < 4) {
        n <- n +1
        next
    }
    print(n)   # solo pasa por aca cuando n >= 4.
    if (n > 6)
        break  # interrupe el ciclo cuando n > 6.
    n = n + 1
}
print('fin')

[1] 4
[1] 5
[1] 6
[1] 7
[1] "fin"


# Funciones

[Contenido](#Contenido)

Las funciones son definidas mediante la palabra reservada `function`. En el siguiente ejemplo se presenta una función que calcula la serie de Fibonnaci. 

In [11]:
fib <- function(n){    
    ## Imprime los términos de la serie de Fibbonaci que son menores que n.
    a <- 0
    b <- 1
    while (a < n) {
        cat(a, end=' ')
        a <- b
        b <- a + b
    }
    cat('\n')
}
# Llama la función
fib(2000)

0  1  2  4  8  16  32  64  128  256  512  1024  


In [12]:
fib  # la función es un objeto.

function(n){    
    ##<c2><a0>Imprime los t<c3><a9>rminos de la serie de Fibbonaci que son menores que n.
    a <- 0
    b <- 1
    while (a < n) {
        cat(a, end=' ')
        a <- b
        b <- a + b
    }
    cat('\n')
}

In [13]:
f = fib # se almacena el objeto en la variable f

In [14]:
f(100)  # terminos de la serie de Fibbonaci menores que 100

0  1  2  4  8  16  32  64  


In [15]:
# en vez de imprimir, devuelve los términos de la serie en un vector.
fib2 <- function(n){
    # Retorna los términos de la serie de Fibbonaci que son menores que n en una lista.
    result = c()  # se crea un vector vacio
    a <- 0
    b <- 1
    while (a < n) {        
        result <- c(result, a)    # se agrega a al final del vector (opera como un stack)
        a <- b
        b <- a + b
    }
    result
}
f100 = fib2(100)    # llama la función
f100                # imprime el resultado

[1]  0  1  2  4  8 16 32 64

In [16]:
f <- function(a=1, b=2) {
    c(a, b)
}

print(f())
print(f(a=5))
print(f(b=10))
print(f(a=5, b=10))

[1] 1 2
[1] 5 2
[1]  1 10
[1]  5 10


Las funciones pueden ser invocadas con una cantidad variable de argumentos.   

In [17]:
f <- function(...){ # simplemente imprime los argumentos con que se invoca
    print(c(...))
}
    
f(1, 2, 3)

[1] 1 2 3


In [18]:
f <- function(...){ # simplemente imprime los argumentos con que se invoca
    print(list(...))
}
    
f(1, 2, 3)

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3



En el siguiente ejemplo, se está dando un valor por defecto al argumento `c`, tal que cuando la función es invocada, la variable `c` toma el valor especificado. 

In [19]:
f <- function(a, ..., d = 'hola'){ 
    print(a)
    print(c(...))
    print(d)
}
    
f(1, 2, 3, 4, 5) # el 5 no se asigna a la variable d

[1] 1
[1] 2 3 4 5
[1] "hola"


Note que a diferencia del caso anterior, en el cual se hacia la llamada `f(1, 2, 3, 4, 5) `, en el siguiente ejemplo se hace explicita la asignación a la variable `c`.

In [20]:
f(1, 2, 3, 4, d=5) # se debe indicar explicitamente que `c = 5`.

[1] 1
[1] 2 3 4
[1] 5


R permite el uso de funciones anónimas (que no se almacenan en una variable). En el siguiente ejemplo, se define la función `incr` la cual incrementa en la unidad su argumento.

In [21]:
incr <- function(x) return(x + 1)

incr(1)

[1] 2

La función puede usarse directamente como una función anónima.

In [22]:
(function(x) x + 1)(1) 

[1] 2

Las funciones pueden retornar funciones, tal como es el caso presentado a continuación donde `return` devuelve una función. Note que el valor de `n` persiste, tal que la función `f` suma `42` a su argumento y `g` suma `1` a su argumento.  

In [23]:
make_incrementor <- function(n){ 
    return (function(x) x + n)
}

f <- make_incrementor(42)
f(0)

[1] 42

In [24]:
f(1)

[1] 43

In [25]:
g <- make_incrementor(1)
g(1)

[1] 2

# Estructuras de Datos

[Contenido](#Contenido)

## Vectores

[Contenido](#Contenido)

In [26]:
a = c(1, 2, 3, 4, 5) # creación de la lista
a

[1] 1 2 3 4 5

In [27]:
a <- c(a, 6) # agrega el elemento al final
a

[1] 1 2 3 4 5 6

In [28]:
b <- c(7, 8, 9)  # crea un nuevo vector
a <- c(a, b)    # pega el nuevo vector al final del anterior
a

[1] 1 2 3 4 5 6 7 8 9

In [29]:
append(a, 0, 2)  # agrega el elemento 0 al vector despues de la posición 2

[1] 1 2 0 3 4 5 6 7 8 9

In [30]:
x = c('a', 'b', 'b', 'c', 'c', 'c', 'd', 'd', 'd', 'd') # cuenta la cantidad de veces que aparece cada elemento
table(x)

x
a b c d 
1 2 3 4 

In [31]:
x <- 1:10
x[-2]  # remueve el elemento en la posición 2

[1]  1  3  4  5  6  7  8  9 10

In [32]:
x <- c(1:4, 1:4, 1:4)
x[x != 1] # remueve los elementos iguales a 1

[1] 2 3 4 2 3 4 2 3 4

In [33]:
rev(1:10)  # invierte el vector

[1] 10  9  8  7  6  5  4  3  2  1

In [34]:
sort(c(2, 4, 1, 5, 3))  # ordena el vector

[1] 1 2 3 4 5

In [35]:
x <- 1:10
x[-length(x)] # elimina el último elemento del vector.

[1] 1 2 3 4 5 6 7 8 9

In [36]:
x = seq(10) # devuelve una lista
x

[1]  1  2  3  4  5  6  7  8  9 10

## Matrices

[Contenido](#Contenido)

R permite la operación directa sobre matrices.

In [3]:
x <- matrix(1:12, nrow = 4, ncol = 3)
print(x)

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12


In [1]:
p<- matrix(1:12, nrow=3, ncol= 4)
print(p)

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12


In [38]:
c(x)

[1]  1  2  3  4  5  6  7  8  9 10 11 12

In [39]:
print(t(x))

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    6    7    8
[3,]    9   10   11   12


In [40]:
print(cbind(c(1,2,3),c(4,5,6)))  # pega por columnas

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6


In [41]:
print(rbind(c(1,2,3),c(4,5,6))) # pega por filas

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6


In [42]:
x[1,]

[1] 1 5 9

In [43]:
x[,1]

[1] 1 2 3 4

In [44]:
x[c(2,3), 2]

[1] 6 7

In [6]:
x[c(1,2,3), 3] #mostrar la los elementos de las filas 1, 2 y 3 para la columna 3

[1]  9 10 11

In [45]:
x[x>5]  # selección lógica

[1]  6  7  8  9 10 11 12

In [46]:
x[x<4] <- 0
print(x)

     [,1] [,2] [,3]
[1,]    0    5    9
[2,]    0    6   10
[3,]    0    7   11
[4,]    4    8   12


In [47]:
x <- matrix(0, 4, 4)
x[seq(1,16, by = 5)] <- 1
print(x)

     [,1] [,2] [,3] [,4]
[1,]    1    0    0    0
[2,]    0    1    0    0
[3,]    0    0    1    0
[4,]    0    0    0    1


In [48]:
y <- matrix(1:16, 4, 4)
print(x + y)

     [,1] [,2] [,3] [,4]
[1,]    2    5    9   13
[2,]    2    7   10   14
[3,]    3    7   12   15
[4,]    4    8   12   17


In [49]:
print(x * y)

     [,1] [,2] [,3] [,4]
[1,]    1    0    0    0
[2,]    0    6    0    0
[3,]    0    0   11    0
[4,]    0    0    0   16


In [50]:
print(x %*% y)

     [,1] [,2] [,3] [,4]
[1,]    1    5    9   13
[2,]    2    6   10   14
[3,]    3    7   11   15
[4,]    4    8   12   16


In [51]:
print(solve(x))  # inversa

     [,1] [,2] [,3] [,4]
[1,]    1    0    0    0
[2,]    0    1    0    0
[3,]    0    0    1    0
[4,]    0    0    0    1


In [52]:
print(x + 1)

     [,1] [,2] [,3] [,4]
[1,]    2    1    1    1
[2,]    1    2    1    1
[3,]    1    1    2    1
[4,]    1    1    1    2


## Funciones `lapply` ,  `apply` 

[Contenido](#Contenido)

In [53]:
x <- 1:6
sqrd <- function(x) x ** 2
lapply(x, sqrd)  # aplica la función a cada elemento y devuelve una lista

[[1]]
[1] 1

[[2]]
[1] 4

[[3]]
[1] 9

[[4]]
[1] 16

[[5]]
[1] 25

[[6]]
[1] 36

In [7]:
x <- matrix(1:16, 4, 4)
print(x)

     [,1] [,2] [,3] [,4]
[1,]    1    5    9   13
[2,]    2    6   10   14
[3,]    3    7   11   15
[4,]    4    8   12   16


In [55]:
print(apply(x, 1, sum))  # aplica la función a cada fila

[1] 28 32 36 40


In [56]:
print(apply(x, 2, sum))  # aplica la función a cada columna

[1] 10 26 42 58


In [9]:
print(apply(x, 1, mean ))

[1]  7  8  9 10


## Data frames

[Contenido](#Contenido)

Los dataframes son la estructura base para almacenar tablas en R. Son ampliamente usados en diferentes funciones para realizar cálculos y estimar modelos. 

In [10]:
x <- 1:5
y <- x ** 2
d <- data.frame(x, y)
print(d)

  x  y
1 1  1
2 2  4
3 3  9
4 4 16
5 5 25


In [58]:
print(d['x']) # acceso a los elementos usando el nombre de las columnas

  x
1 1
2 2
3 3
4 4
5 5


In [59]:
print(d['y'])

   y
1  1
2  4
3  9
4 16
5 25


In [60]:
print(d[2:4,])  # acceso como una matriz

  x  y
2 2  4
3 3  9
4 4 16


In [61]:
print(d[2:4,2])

[1]  4  9 16


In [62]:
d$x  # acceso como una lista

[1] 1 2 3 4 5

In [63]:
d$y # acceso como una lista

[1]  1  4  9 16 25

In [64]:
print(head(d, n = 3)) # imprime los primeros tres registros

  x y
1 1 1
2 2 4
3 3 9


In [65]:
print(tail(d, n = 3))  # imprime los ultimos tres registros

  x  y
3 3  9
4 4 16
5 5 25


In [66]:
d$nuevo = c('a', 'a', 'b', 'c', 'd')  # agrega una nueva columna

In [67]:
print(d)

  x  y nuevo
1 1  1     a
2 2  4     a
3 3  9     b
4 4 16     c
5 5 25     d


In [13]:
d$nombre = c('m', 'i', 'l', 't', 'n')
print(d)

  x  y nombre
1 1  1      m
2 2  4      i
3 3  9      l
4 4 16      t
5 5 25      n


In [68]:
str(d)

'data.frame':	5 obs. of  3 variables:
 $ x    : int  1 2 3 4 5
 $ y    : num  1 4 9 16 25
 $ nuevo: chr  "a" "a" "b" "c" ...


In [69]:
print(d[-2,])  # elimina la segunda fila

  x  y nuevo
1 1  1     a
3 3  9     b
4 4 16     c
5 5 25     d


In [70]:
print(d[,-2]) # elimina la segunda columna

  x nuevo
1 1     a
2 2     a
3 3     b
4 4     c
5 5     d


In [71]:
print(rbind(d, c(6, 36, 'f')))

  x  y nuevo
1 1  1     a
2 2  4     a
3 3  9     b
4 4 16     c
5 5 25     d
6 6 36     f


In [72]:
print(cbind(d, m = seq(from=10, to=50, by=10)))

  x  y nuevo  m
1 1  1     a 10
2 2  4     a 20
3 3  9     b 30
4 4 16     c 40
5 5 25     d 50


## Conjuntos

[Contenido](#Contenido)

R no posee conjuntos propiamente dichos, pero es posible aplicar las funciones de conjuntos a vectores.

In [73]:
x = c(1:5, 1:5, 1:5)
print(x) 

 [1] 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5


In [74]:
print(unique(x))  # extrae los elementos únicos

[1] 1 2 3 4 5


In [75]:
duplicated(x) # indica los elementos duplicados

[1] FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[13]  TRUE  TRUE  TRUE

In [76]:
x <- 1:7
y <- 5:10
print(union(x, y))

 [1]  1  2  3  4  5  6  7  8  9 10


In [77]:
print(intersect(x, y))

[1] 5 6 7


In [78]:
print(setdiff(x, y))

[1] 1 2 3 4


In [79]:
print(setequal(x, y))

[1] FALSE


In [80]:
print(1 %in% x)

[1] TRUE


## Uso de listas como dicionarios

[Contenido](#Contenido)

A diferencia de Python, R no posee diccionarios, pero pueden simularse usando listas o vectores.

In [81]:
tel = c(jack=4098, sape=4139) # 'jack'  y 'sape'actuan como claves y 4098 y 4139 son los valores
tel['guido'] = 4127  # se agrega un neuvo elemento al dicicionario.
tel

jack  sape guido 
 4098  4139  4127

In [82]:
tel['jack']  # se obtiene el valor asociado a la clave 'jack'

jack 
4098

In [83]:
names(tel)    # la función `names` imprime los nombres de los elementos.

[1] "jack"  "sape"  "guido"

In [84]:
sort(names(tel))  # nombres ordenados.

[1] "guido" "jack"  "sape"

In [85]:
'irv' %in% names(tel)  

[1] FALSE

## Factores

[Contenido](#Contenido)

Los factores son variables categóricas, usualmente ordenadas, que representan clases.  

In [86]:
x <- factor(c("A","B","B","A"))
print(x)

[1] A B B A
Levels: A B


In [87]:
str(x)

 Factor w/ 2 levels "A","B": 1 2 2 1


In [88]:
x <- factor(c("A","B","B","A"), levels = c('A', 'B', 'C'))
print(x)

[1] A B B A
Levels: A B C


In [89]:
str(x)

 Factor w/ 3 levels "A","B","C": 1 2 2 1


In [90]:
x[2]

[1] B
Levels: A B C

In [91]:
x[2] <- 'C'  # se cambia el nivel 

In [92]:
print(x)

[1] A C B A
Levels: A B C


In [93]:
levels(x) <- c(levels(x), 'E') # se agrega un nuevo nivel
str(x)

 Factor w/ 4 levels "A","B","C","E": 1 3 2 1


## Strings

[Contenido](#Contenido)

In [94]:
toupper('hola mundo')

[1] "HOLA MUNDO"

In [95]:
tolower('HOLA MUNDO')

[1] "hola mundo"

---

**Ejercicio.--** Escriba una función equivalente a la función `swapcase` para los strings en Python.

In [1]:
swapcase('Hola Mundo')

ERROR: Error in eval(expr, envir, enclos): no se pudo encontrar la función "swapcase"


**Ejercicio.--** Escriba una función equivalente a la función `title` para los strings en Python.

**Ejercicio.--** Escriba una función equivalente a la función `center` para los strings en Python.

**Ejercicio.--** Escriba una función equivalente a la función `ljust` para los strings en Python.

**Ejercicio.--** Escriba una función equivalente a la función `rjust` para los strings en Python.

**Ejercicio.--** Escriba una función equivalente a la función `count` para los strings en Python.

**Ejercicio.--** Escriba una función equivalente a la función `isalnum` para los strings en Python.

**Ejercicio.--** Escriba una función equivalente a la función `isalpha` para los strings en Python.

**Ejercicio.--** Escriba una función equivalente a la función `isdigit` para los strings en Python.

**Ejercicio.--** Escriba una función equivalente a la función `splitlines` para los strings en Python.

---

In [96]:
strsplit('1,2,3,4,5', ',')

[[1]]
[1] "1" "2" "3" "4" "5"

`grep` retorna un vector de enteros que indican la posición de los strings que cumplen con un patrón.

In [97]:
sprintf('%g', 1:20)

[1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12" "13" "14" "15"
[16] "16" "17" "18" "19" "20"

In [98]:
x <- sprintf('%g', 1:20)
x[grep('1', x)]
grep('1', x)

[1] "1"  "10" "11" "12" "13" "14" "15" "16" "17" "18" "19"

[1]  1 10 11 12 13 14 15 16 17 18 19

In [99]:
x <- sprintf('%g', 1:100)
x[grep('1$', x)]  # **Imprima los números del 1 al 100 que finalicen con un '1'.**

[1] "1"  "11" "21" "31" "41" "51" "61" "71" "81" "91"

In [100]:
x <- sprintf('%g', 1:100)
x[grep('^1', x)] # **Imprima los números del 1 al 100 que empiecen con un '1'.**

[1] "1"   "10"  "11"  "12"  "13"  "14"  "15"  "16"  "17"  "18"  "19"  "100"

In [101]:
x <- sprintf('%g', 1:20)
length(x[grep('1', x)])

[1] 11

In [102]:
x <- c("123456790",
       "abcdefghi",
      "jklmnopqr" )
substring(x, first=3, last=5)

[1] "345" "cde" "lmn"

# Impresión con formato

[Contenido](#Contenido)

In [103]:
s <- 'Hello, world.'
print(s) # note que aca lo imprime con las comillas

[1] "Hello, world."


In [104]:
str(s) # imprime el tipo

 chr "Hello, world."


In [105]:
cat(s) # imprime sin las comillas

Hello, world.

In [106]:
a = 12  
as.character(a)  # convierte al 1 de número a string.

[1] "12"

In [107]:
as.character(1/7)

[1] "0.142857142857143"

La función `cat()` es usualmente usada para la concatenación de strings, tal como se ilustra en el siguiente ejemplo.

In [108]:
x = 10 * 3.25
y = 200 * 200
s = paste('The value of x is ', x, ', and y is ', y, '...')
cat(s)

The value of x is  32.5 , and y is  40000 ...

In [109]:
cat("linea 1", "linea 2", "linea 3")

linea 1 linea 2 linea 3

In [110]:
cat("linea 1", "linea 2", "linea 3", sep='-', end='***')

linea 1-linea 2-linea 3-***

In [111]:
cat("linea 1", "linea 2", "linea 3", sep='\n', end='***')

linea 1
linea 2
linea 3
***


In [112]:
cat(x, y, c('spam', 'eggs'))

32.5 40000 spam eggs

In [113]:
for (x in seq(10)) {
    cat(sprintf('%2d  %3d %4d\n', x, x^2, x^3))
}

 1    1    1
 2    4    8
 3    9   27
 4   16   64
 5   25  125
 6   36  216
 7   49  343
 8   64  512
 9   81  729
10  100 1000


In [114]:
print(sprintf('%5d', 5))

[1] "    5"


In [115]:
print(sprintf('%-5d', 5))

[1] "5    "


In [116]:
print(sprintf('%05d', 5))

[1] "00005"


In [117]:
print(sprintf('%05d', -3))

[1] "-0003"


In [118]:
print(sprintf('%5.2f', 3.14159265359))

[1] " 3.14"


In [119]:
cat(sprintf('Este es el argumento %s y este el "%s"', '-1-', '-2-'))

Este es el argumento -1- y este el "-2-"

In [120]:
print(sprintf('%s ---- %f', 'hola mundo', 1.23456789))

[1] "hola mundo ---- 1.234568"


In [121]:
print(sprintf('%15s ---- %8.2f', 'hola mundo', 1.23456789))

[1] "     hola mundo ----     1.23"


In [122]:
print(sprintf('%-15s ---- %8.2f', 'hola mundo', 1.23456789))

[1] "hola mundo      ----     1.23"


In [123]:
sprintf('linea %d', 1:5)

[1] "linea 1" "linea 2" "linea 3" "linea 4" "linea 5"

In [124]:
sprintf('%d,', seq(5))

[1] "1," "2," "3," "4," "5,"

In [125]:
cat(sprintf('%d', seq(5)), sep=',')

1,2,3,4,5

In [126]:
cat(sprintf('%d,', seq(5)), sep='')

1,2,3,4,5,

In [127]:
x <- list(Sjoerd=4127, Jack=4098, Dcab=7678)
for (z in names(x)) {
    print(sprintf('%-10s   ==> %10d', z, x[[z]]))
} 

[1] "Sjoerd       ==>       4127"
[1] "Jack         ==>       4098"
[1] "Dcab         ==>       7678"


# Ejecución de Python dentro de R

[Contenido](#Contenido)

Instale el paquete rPython desde el depósito del CRAN.

Use el siguiente ejemplo para verificar que su instalación fue correcta

In [128]:
library(rPython)
a <- 1:4
python.assign( "a", a )
python.exec( "b = len( a )" )
python.get( "b" )

Loading required package: RJSONIO


[1] 4

In [129]:
a <- 1:4
b <- 5:8
python.exec( "def concat(a,b): return a+b" )
python.call( "concat", a, b)

[1] 1 2 3 4 5 6 7 8

---

[Contenido](#Contenido)

<a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Licencia de Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png" /></a><br />Este obra está bajo una <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">licencia de Creative Commons Reconocimiento-NoComercial-SinObraDerivada 4.0 Internacional</a>.